services:
  pia-qbittorrent:
    image: j4ym0/pia-qbittorrent
    container_name: pia-qbittorrent
    ports:
      - 8889:8888
    cap_add:
      - NET_ADMIN
    environment:
      - UID=99
      - GID=100
      - REGION=Japan
      - USER=${PIA_USER}
      - PASSWORD=${PIA_PASSWORD}
      - PORT_FORWARDING=true
      - LEGACY_IPTABLES=true
      - TZ=Asia/Tokyo
    volumes:
      - /mnt/user/appdata/qbittorrent:/config
      - /mnt/user/appdata/qbittorrent/etc:/etc
      - /mnt/user/Downloads:/downloads
    labels:
      net.unraid.docker.icon: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/qbittorrent.png"
      net.unraid.docker.webui: "http://[IP]:[PORT:8889]/"
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    depends_on:
      - pia-qbittorrent
    ports:
      - 8989:8989
    environment:
      - PUID=99
      - PGID=100
      - TZ=Asia/Tokyo
    volumes:
      - /mnt/user/appdata/sonarr:/config
      - /mnt/user/Media/Series:/tv
      - /mnt/user/Downloads:/downloads
    labels:
      net.unraid.docker.icon: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/sonarr.png"
      net.unraid.docker.webui: "http://[IP]:[PORT:8989]/"

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    depends_on:
      - pia-qbittorrent
    ports:
      - 7878:7878
    environment:
      - PUID=99
      - PGID=100
      - TZ=Asia/Tokyo
    volumes:
      - /mnt/user/appdata/radarr:/config
      - /mnt/user/Media/Movies:/movies
      - /mnt/user/Downloads:/downloads
    labels:
      net.unraid.docker.icon: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/radarr.png"
      net.unraid.docker.webui: "http://[IP]:[PORT:7878]/"

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    depends_on:
      - pia-qbittorrent
    ports:
      - 6767:6767
    environment:
      - PUID=99
      - PGID=100
      - TZ=Asia/Tokyo
    volumes:
      - /mnt/user/appdata/bazarr:/config
      - /mnt/user/Media/Movies:/movies
      - /mnt/user/Media/Series:/tv
      - /mnt/user/Downloads:/downloads
    labels:
      net.unraid.docker.icon: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/bazarr.png"
      net.unraid.docker.webui: "http://[IP]:[PORT:6767]/"

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    restart: unless-stopped
    depends_on:
      - pia-qbittorrent
    ports:
      - 9117:9117
    environment:
      - PUID=99
      - PGID=100
      - TZ=Asia/Tokyo
    volumes:
      - /mnt/user/appdata/jackett:/config
      - /mnt/user/Downloads:/downloads
    labels:
      net.unraid.docker.icon: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/jackett.png"
      net.unraid.docker.webui: "http://[IP]:[PORT:9117]/"

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=99
      - PGID=100
      - TZ=Asia/Tokyo
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - /mnt/user/appdata/Plex-Media-Server:/config
      - /mnt/user/Media/Series:/tv
      - /mnt/user/Media/Movies:/movies
      - /mnt/user/Media/Music:/music
    deploy:
      resources:
        limits:
          memory: 4G
    labels:
      net.unraid.docker.icon: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/plex.png"
      net.unraid.docker.webui: "http://[IP]:32400/web"
