services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=5050
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "${TAILSCALE_IP}:5050:5050"
    deploy:
      resources:
        limits:
          memory: 256M

volumes:
  pgadmin_data:
