type = "http"
name = "Prod: Backend Health"
url = "https://api.nadeshiko.co/up"
interval = 60
max_retries = 3
retry_interval = 30
accepted_statuscodes = ["200-299"]
expiry_notification = true
notification_name_list = ["discord"]
parent_name = "nadeshiko"
