type = "http"
name = "Dev: Frontend Health"
url = "https://dev.nadeshiko.co/up"
interval = 300
max_retries = 3
retry_interval = 30
accepted_statuscodes = ["200-299"]
notification_name_list = ["discord"]
parent_name = "nadeshiko"
