type = "http"
name = "Prod: SSL Frontend"
url = "https://nadeshiko.co"
interval = 86400
max_retries = 1
retry_interval = 60
accepted_statuscodes = ["200-299"]
expiry_notification = true
notification_name_list = ["discord"]
parent_name = "nadeshiko"
