services:
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    network_mode: host
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    deploy:
      resources:
        limits:
          memory: 128M
    logging:
      options:
        max-size: 50m
        max-file: "3"
